# We use a hardcoded image so that startup is much faster (don't want users waiting for Gitpod to build the Docker image)
image: mieubrisse/playground-gitpod-base

tasks:
  - name: Kurtosis
    command: |
      # This script is bundled inside the Docker image
      bash /home/gitpod/.setup/run-gitpod-init.sh

      # Allow users to overwrite the SL script contents via URL variables
      if [ -n "${KURTOSIS_SL_SCRIPT_CONTENTS}" ]; then
        echo "${KURTOSIS_SL_SCRIPT_CONTENTS}" > /workspace/playground-gitpod/fresh-package/main.star
        code /workspace/playground-gitpod/fresh-package/main.star
      fi

ports:
  - name: Kurtosis Engine GRPC Port
    description: The Kurtosis engine's GRPC listen port
    port: 9710
    onOpen: ignore
    # TODO Delete this when https://github.com/kurtosis-tech/kurtosis/issues/560 is fixed
  - name: (DEPRECATEDD) Kurtosis Engine GRPC Proxy Port
    description: The Kurtosis engine's deprecated GRPC proxy listen port
    port: 9711
    onOpen: ignore

vscode:
  extensions:
    - Kurtosis.kurtosis-extension
