# We use a hardcoded image so that startup is much faster (don't want users waiting for Gitpod to build the Docker image)
image: mieubrisse/playground-gitpod-base

tasks:
  - name: Kurtosis
    command: |
      # This script is bundled inside the Docker image
      bash /setup/run-gitpod-init.sh

ports:
  - name: Kurtosis Engine GRPC Port
    description: The Kurtosis engine's GRPC listen port
    port: 9710
    onOpen: ignore

vscode:
  extensions:
    - Kurtosis.kurtosis-extension
